### ISSUE TITLE
Open Manipulator Controller with MoveIt option

### ISSUE THREAD

**Issue by fatihirim** [ROBOTIS-GIT/open_manipulator#73]
Hello

I try to launch Open Manipulator Controller with MoveIt Option. I follow the instructions on your e-manual page for Open Manipulator. However when I run he following command:

`roslaunch open_manipulator_controller open_manipulator_controller.launch use_moveit:=true`

I get the error:

```
started roslaunch server http://robut-linux-1:36685/

SUMMARY
========

PARAMETERS
 * /move_group/allow_trajectory_execution: False
 * /move_group/arm/default_planner_config: RRTConnect
 * /move_group/arm/longest_valid_segment_fraction: 0.005
 * /move_group/arm/planner_configs: ['SBL', 'EST', 'L...
 * /move_group/arm/projection_evaluator: joints(joint1,joi...
 * /move_group/capabilities: 
 * /move_group/disable_capabilities: 
 * /move_group/jiggle_fraction: 0.05
 * /move_group/max_safe_path_cost: 1
 * /move_group/planner_configs/BFMT/balanced: 0
 * /move_group/planner_configs/BFMT/cache_cc: 1
 * /move_group/planner_configs/BFMT/extended_fmt: 1
 * /move_group/planner_configs/BFMT/heuristics: 1
 * /move_group/planner_configs/BFMT/nearest_k: 1
 * /move_group/planner_configs/BFMT/num_samples: 1000
 * /move_group/planner_configs/BFMT/optimality: 1
 * /move_group/planner_configs/BFMT/radius_multiplier: 1.0
 * /move_group/planner_configs/BFMT/type: geometric::BFMT
 * /move_group/planner_configs/BKPIECE/border_fraction: 0.9
 * /move_group/planner_configs/BKPIECE/failed_expansion_score_factor: 0.5
 * /move_group/planner_configs/BKPIECE/min_valid_path_fraction: 0.5
 * /move_group/planner_configs/BKPIECE/range: 0.0
 * /move_group/planner_configs/BKPIECE/type: geometric::BKPIECE
 * /move_group/planner_configs/BiEST/range: 0.0
 * /move_group/planner_configs/BiEST/type: geometric::BiEST
 * /move_group/planner_configs/BiTRRT/cost_threshold: 1e300
 * /move_group/planner_configs/BiTRRT/frountier_node_ratio: 0.1
 * /move_group/planner_configs/BiTRRT/frountier_threshold: 0.0
 * /move_group/planner_configs/BiTRRT/init_temperature: 100
 * /move_group/planner_configs/BiTRRT/range: 0.0
 * /move_group/planner_configs/BiTRRT/temp_change_factor: 0.1
 * /move_group/planner_configs/BiTRRT/type: geometric::BiTRRT
 * /move_group/planner_configs/EST/goal_bias: 0.05
 * /move_group/planner_configs/EST/range: 0.0
 * /move_group/planner_configs/EST/type: geometric::EST
 * /move_group/planner_configs/FMT/cache_cc: 1
 * /move_group/planner_configs/FMT/extended_fmt: 1
 * /move_group/planner_configs/FMT/heuristics: 0
 * /move_group/planner_configs/FMT/nearest_k: 1
 * /move_group/planner_configs/FMT/num_samples: 1000
 * /move_group/planner_configs/FMT/radius_multiplier: 1.1
 * /move_group/planner_configs/FMT/type: geometric::FMT
 * /move_group/planner_configs/KPIECE/border_fraction: 0.9
 * /move_group/planner_configs/KPIECE/failed_expansion_score_factor: 0.5
 * /move_group/planner_configs/KPIECE/goal_bias: 0.05
 * /move_group/planner_configs/KPIECE/min_valid_path_fraction: 0.5
 * /move_group/planner_configs/KPIECE/range: 0.0
 * /move_group/planner_configs/KPIECE/type: geometric::KPIECE
 * /move_group/planner_configs/LBKPIECE/border_fraction: 0.9
 * /move_group/planner_configs/LBKPIECE/min_valid_path_fraction: 0.5
 * /move_group/planner_configs/LBKPIECE/range: 0.0
 * /move_group/planner_configs/LBKPIECE/type: geometric::LBKPIECE
 * /move_group/planner_configs/LBTRRT/epsilon: 0.4
 * /move_group/planner_configs/LBTRRT/goal_bias: 0.05
 * /move_group/planner_configs/LBTRRT/range: 0.0
 * /move_group/planner_configs/LBTRRT/type: geometric::LBTRRT
 * /move_group/planner_configs/LazyPRM/range: 0.0
 * /move_group/planner_configs/LazyPRM/type: geometric::LazyPRM
 * /move_group/planner_configs/LazyPRMstar/type: geometric::LazyPR...
 * /move_group/planner_configs/PDST/type: geometric::PDST
 * /move_group/planner_configs/PRM/max_nearest_neighbors: 10
 * /move_group/planner_configs/PRM/type: geometric::PRM
 * /move_group/planner_configs/PRMstar/type: geometric::PRMstar
 * /move_group/planner_configs/ProjEST/goal_bias: 0.05
 * /move_group/planner_configs/ProjEST/range: 0.0
 * /move_group/planner_configs/ProjEST/type: geometric::ProjEST
 * /move_group/planner_configs/RRT/goal_bias: 0.05
 * /move_group/planner_configs/RRT/range: 0.0
 * /move_group/planner_configs/RRT/type: geometric::RRT
 * /move_group/planner_configs/RRTConnect/range: 0.0
 * /move_group/planner_configs/RRTConnect/type: geometric::RRTCon...
 * /move_group/planner_configs/RRTstar/delay_collision_checking: 1
 * /move_group/planner_configs/RRTstar/goal_bias: 0.05
 * /move_group/planner_configs/RRTstar/range: 0.0
 * /move_group/planner_configs/RRTstar/type: geometric::RRTstar
 * /move_group/planner_configs/SBL/range: 0.0
 * /move_group/planner_configs/SBL/type: geometric::SBL
 * /move_group/planner_configs/SPARS/dense_delta_fraction: 0.001
 * /move_group/planner_configs/SPARS/max_failures: 1000
 * /move_group/planner_configs/SPARS/sparse_delta_fraction: 0.25
 * /move_group/planner_configs/SPARS/stretch_factor: 3.0
 * /move_group/planner_configs/SPARS/type: geometric::SPARS
 * /move_group/planner_configs/SPARStwo/dense_delta_fraction: 0.001
 * /move_group/planner_configs/SPARStwo/max_failures: 5000
 * /move_group/planner_configs/SPARStwo/sparse_delta_fraction: 0.25
 * /move_group/planner_configs/SPARStwo/stretch_factor: 3.0
 * /move_group/planner_configs/SPARStwo/type: geometric::SPARStwo
 * /move_group/planner_configs/STRIDE/degree: 16
 * /move_group/planner_configs/STRIDE/estimated_dimension: 0.0
 * /move_group/planner_configs/STRIDE/goal_bias: 0.05
 * /move_group/planner_configs/STRIDE/max_degree: 18
 * /move_group/planner_configs/STRIDE/max_pts_per_leaf: 6
 * /move_group/planner_configs/STRIDE/min_degree: 12
 * /move_group/planner_configs/STRIDE/min_valid_path_fraction: 0.2
 * /move_group/planner_configs/STRIDE/range: 0.0
 * /move_group/planner_configs/STRIDE/type: geometric::STRIDE
 * /move_group/planner_configs/STRIDE/use_projected_distance: 0
 * /move_group/planner_configs/TRRT/frountierNodeRatio: 0.1
 * /move_group/planner_configs/TRRT/frountier_threshold: 0.0
 * /move_group/planner_configs/TRRT/goal_bias: 0.05
 * /move_group/planner_configs/TRRT/init_temperature: 10e-6
 * /move_group/planner_configs/TRRT/k_constant: 0.0
 * /move_group/planner_configs/TRRT/max_states_failed: 10
 * /move_group/planner_configs/TRRT/min_temperature: 10e-10
 * /move_group/planner_configs/TRRT/range: 0.0
 * /move_group/planner_configs/TRRT/temp_change_factor: 2.0
 * /move_group/planner_configs/TRRT/type: geometric::TRRT
 * /move_group/planning_plugin: ompl_interface/OM...
 * /move_group/planning_scene_monitor/publish_geometry_updates: True
 * /move_group/planning_scene_monitor/publish_planning_scene: True
 * /move_group/planning_scene_monitor/publish_state_updates: True
 * /move_group/planning_scene_monitor/publish_transforms_updates: True
 * /move_group/request_adapters: industrial_trajec...
 * /move_group/sample_duration: 0.05
 * /move_group/smoothing_5_coef: [0.25, 0.5, 1.0, ...
 * /move_group/smoothing_filter_name: /move_group/smoot...
 * /move_group/start_state_max_bounds_error: 0.1
 * /open_manipulator/control_period: 0.01
 * /open_manipulator/moveit_sample_duration: 0.05
 * /open_manipulator/planning_group_name: arm
 * /open_manipulator/using_moveit: True
 * /open_manipulator/using_platform: True
 * /robot_description: <?xml version="1....
 * /robot_description_kinematics/arm/kinematics_solver: kdl_kinematics_pl...
 * /robot_description_kinematics/arm/kinematics_solver_attempts: 3
 * /robot_description_kinematics/arm/kinematics_solver_search_resolution: 0.005
 * /robot_description_kinematics/arm/kinematics_solver_timeout: 0.005
 * /robot_description_kinematics/arm/position_only_ik: False
 * /robot_description_planning/joint_limits/joint1/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/joint1/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint1/max_acceleration: 0
 * /robot_description_planning/joint_limits/joint1/max_velocity: 4.8
 * /robot_description_planning/joint_limits/joint2/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/joint2/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint2/max_acceleration: 0
 * /robot_description_planning/joint_limits/joint2/max_velocity: 4.8
 * /robot_description_planning/joint_limits/joint3/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/joint3/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint3/max_acceleration: 0
 * /robot_description_planning/joint_limits/joint3/max_velocity: 4.8
 * /robot_description_planning/joint_limits/joint4/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/joint4/has_velocity_limits: True
 * /robot_description_planning/joint_limits/joint4/max_acceleration: 0
 * /robot_description_planning/joint_limits/joint4/max_velocity: 4.8
 * /robot_description_semantic: <?xml version="1....
 * /rosdistro: kinetic
 * /rosversion: 1.12.13
 * /rviz_robut_linux_1_31430_7019979553358795822/arm/kinematics_solver: kdl_kinematics_pl...
 * /rviz_robut_linux_1_31430_7019979553358795822/arm/kinematics_solver_attempts: 3
 * /rviz_robut_linux_1_31430_7019979553358795822/arm/kinematics_solver_search_resolution: 0.005
 * /rviz_robut_linux_1_31430_7019979553358795822/arm/kinematics_solver_timeout: 0.005
 * /rviz_robut_linux_1_31430_7019979553358795822/arm/position_only_ik: False

NODES
  /
    move_group (moveit_ros_move_group/move_group)
    open_manipulator (open_manipulator_controller/open_manipulator_controller)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    rviz_robut_linux_1_31430_7019979553358795822 (rviz/rviz)

ROS_MASTER_URI=http://localhost:11311

process[robot_state_publisher-1]: started with pid [31450]
process[move_group-2]: started with pid [31451]
process[rviz_robut_linux_1_31430_7019979553358795822-3]: started with pid [31453]
process[open_manipulator-4]: started with pid [31464]
[ INFO] [1546259564.320588893]: rviz version 1.12.16
[ INFO] [1546259564.320645622]: compiled against Qt version 5.5.1
[ INFO] [1546259564.320660222]: compiled against OGRE version 1.9.0 (Ghadamon)
Joint Dynamixel ID : 11, Model Name : XH430-W350
Joint Dynamixel ID : 12, Model Name : XM430-W350
Joint Dynamixel ID : 13, Model Name : XM430-W350
Joint Dynamixel ID : 14, Model Name : XH430-W350
[move_group-2] process has died [pid 31451, exit code -11, cmd /opt/ros/kinetic/lib/moveit_ros_move_group/move_group __name:=move_group __log:=/home/fatih/.ros/log/6cfd1c8a-0cf7-11e9-a895-7cb0c2fe1875/move_group-2.log].
log file: /home/fatih/.ros/log/6cfd1c8a-0cf7-11e9-a895-7cb0c2fe1875/move_group-2*.log
Gripper Dynamixel ID : 15, Model Name :XM430-W210



[ INFO] [1546259564.901577411]: Stereo is NOT SUPPORTED
[ INFO] [1546259564.901652515]: OpenGl version: 3 (GLSL 1.3).
[rviz_robut_linux_1_31430_7019979553358795822-3] process has died [pid 31453, exit code -11, cmd /opt/ros/kinetic/lib/rviz/rviz -d /home/fatih/WORKSPACES/ws_open_manipulator/src/open_manipulator/open_manipulator_moveit/launch/moveit.rviz __name:=rviz_robut_linux_1_31430_7019979553358795822 __log:=/home/fatih/.ros/log/6cfd1c8a-0cf7-11e9-a895-7cb0c2fe1875/rviz_robut_linux_1_31430_7019979553358795822-3.log].
log file: /home/fatih/.ros/log/6cfd1c8a-0cf7-11e9-a895-7cb0c2fe1875/rviz_robut_linux_1_31430_7019979553358795822-3*.log
```

Looks like ROS nodes are dying after started.
Can you help with this error?

**Comment by fatihirim** [comment]
Also in the log of my ros-master, I have the following error:

```
[rosmaster.master][INFO] 2018-12-31 15:32:41,815: publisherUpdate[/tf_static] -> http://robut-linux-1:34029/ []
[rosmaster.master][INFO] 2018-12-31 15:32:41,815: publisherUpdate[/tf_static] -> http://robut-linux-1:34029/ []: sec=0.00, exception=[Errno 111] Connection refused
[rosmaster.threadpool][ERROR] 2018-12-31 15:32:41,815: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosmaster/threadpool.py", line 218, in run
    result = cmd(*args)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosmaster/master_api.py", line 210, in publisher_update_task
    ret = xmlrpcapi(api).publisherUpdate('/master', topic, pub_uris)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1311, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1459, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused
```

Hope this helps in identifying the root cause and a possible solution...

**Comment by fatihirim** [comment]
I get the same error when trying to run demo under moveit package..

**Comment by routiful** [comment]
```
NODES
  /
    move_group (moveit_ros_move_group/move_group)
    open_manipulator (open_manipulator_controller/open_manipulator_controller)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    rviz_robut_linux_1_31430_7019979553358795822 (rviz/rviz)
```

joint_state_publisher was not launched as shown messages you attached.
When did you downloaded packages? check updates and open_manipulator_moveit.launch file
